services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=postgrespw
    ports:
    - 5432:5432
    volumes:
    - /var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
     - 5672:5672
     - 15672:15672  
