services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=postgrespw
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
volumes:
 pgdata:
 mongodb_data:   